### ISSUE TITLE
Connecting with private support channel

### ISSUE THREAD

**Issue by kaxevgg** [mathieudutour/slacking-pigeons#1]
@mathieudutour Can this currently link to a private slack channel? We don't want everyone on the team answering inquiries

**Comment by mathieudutour** [comment]
Hum it’s wouldnt be too hard but it would ask the permission to access the all the private channels. There is no way to restrict the permissions to a specific channel yet. Is that ok?

**Comment by kaxevgg** [comment]
Is that the case with public channels too? Can I specifically select the public #support channel?

**Comment by mathieudutour** [comment]
yes you can select it and I will only access the messages that are in the threads initiated by Slacking Pigeons anyway. But I'm just concerned that granting permissions to private channels might put people off

**Comment by kaxevgg** [comment]
If your scope of access is only threads started by Slack Pigeons then I don't think people will be put off even if private channels are authorized. This would really help big teams in which only a select few are authorized to answer client inquiries

**Comment by kaxevgg** [comment]
Oh also @mathieudutour you should consider opening up a public trello board so people can watch your product roadmap and place ideas in your backlog

**Comment by mathieudutour** [comment]
I'm using GitHub Issues for that :) all my ideas are there: https://github.com/mathieudutour/slacking-pigeons/issues feel free to comment on them or create new one

**Comment by kaxevgg** [comment]
Ahh right ofcourse

I particularly like the way Polymail did it https://trello.com/b/hk4vz8wI/polymail-roadmap

**Comment by kaxevgg** [comment]
Keep me updated about the private channel feature :)

**Comment by mathieudutour** [comment]
yeah I'm building a lightweight roadmap tool linked to github: https://prior.ly/mathieudutour/slacking-pigeons

**Comment by kaxevgg** [comment]
Haha of course you're building your own product. Love it!

**Comment by mathieudutour** [comment]
Should work now!
