### ISSUE TITLE
Allow to change connected channel

### ISSUE THREAD

**Issue by jsander** [mathieudutour/slacking-pigeons#12]
Great app! I ran into the following problem though:

1. added app and selected a private channel to post to
2. removed app after realizing it does not allow to answer messages from private channels
3. re-added app and selected a public channel to post to
4. messages still appear in the previously added private channel

I'd suggest introducing a setting that allows switching the connected channel.

**Comment by mathieudutour** [comment]
Can you tell me your slack team id?

**Comment by mathieudutour** [comment]
You can now specify a `channelId` when rendering the widget. When you add the app, it will tell you what is the id of the channel you selected.

**Comment by jsander** [comment]
It still does not work for me. Even after specifying a different channelId, it still posts to the same private channel. Responses posted on slack do not appear in the website widget.

**Comment by mathieudutour** [comment]
Is it from the same browser as before? Once a thread is started in a channel, it will keep using it, doesn't matter which channelId is specified
