### ISSUE TITLE
Script link doesnt seem to have any javascript and hence the plugin doesnt render anything on the webpage

### ISSUE THREAD

**Issue by kaxevgg** [mathieudutour/slacking-pigeons#13]
@mathieudutour https://slacking-pigeons.com/bundle.js is empty

**Comment by mathieudutour** [comment]
oh my bad, deploying now

**Comment by kaxevgg** [comment]
@mathieudutour Still getting an error in the console

```javascript
WebSocket connection to 'wss://slacking-pigeons.com/socket.io/?socketId=2779465178408&teamId=T37U79RL0&label=default&channel=G3ZACCP4N&EIO=3&transport=websocket&sid=H3dgONsMruerfa-VAAEP' failed: Error during WebSocket handshake: Unexpected response code: 400
```

Messages from slack are not relayed back to chat

**Comment by mathieudutour** [comment]
The 400 error is because the AWS load balancer doesn’t accept websockets. I’ll try to fix that. In the meantime, it’s falling back to polling so should still work, albeit not optimally. 

Regarding the message from slack not relayed: did you perhaps installed it in a private channel?
