### ISSUE TITLE
paper plane icon

### ISSUE THREAD

**Issue by lucademian** [mathieudutour/slacking-pigeons#14]
Here's a screenshot:
![](http://i.imgur.com/LhIK1B8.png)

You can see the icon at the top left of the chat window

**Comment by mathieudutour** [comment]
oh that's super interesting. There is an element with the class used by `font-awesome` but I'm not loading it because it's WIP.

Do you want maybe an extension that loads font awesome? I'll fix anyway but that's pretty interesting

**Comment by lucademian** [comment]
I tried opening in incognito and it didn't show up. Maybe I had that image cached or something and it showed up because of that?

**Comment by mathieudutour** [comment]
yes possibly
