### ISSUE TITLE
string overflow

### ISSUE THREAD

**Issue by lucademian** [mathieudutour/slacking-pigeons#15]
not sure if this is important, but when you type a string that is too long and doesn't have any spaces, it overflows the chat bubble. Something like this: 'overflowtestadasdfweqwlgqlwoigawoidasdgasdgasdgasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf'

**Comment by mathieudutour** [comment]
good catch!
